### PR TITLE
updated edit link on post#show

### PR DESCRIPTION
**Pull request by longdino**
- edited post_param on post controller
- defined edit function from post controller
- added link to edit posts on post#show

### CODE REVIEW

**Comment by longdino** [comment]
I added development.log on this pull request because I thought we need to keep it. If not, then I'll do git pull without this file.

**Comment by ccci210** [comment]
There is a merge conflict in the log/development.log file. The file is too large so it's difficult to resolve the conflict. I think that you can just remove it.

**Review by ccci210 — CHANGES_REQUESTED** [review]
There is a merge conflict in the log/development.log file. The file is too large so it's difficult to resolve the conflict. I think that you can just remove it.

**Comment by longdino** [comment]
> There is a merge conflict in the log/development.log file. The file is too large so it's difficult to resolve the conflict. I think that you can just remove it.

Okay! Let me re-do this

**Pull request closed without merging**
